name: Super-Linter

# Run this workflow on every PR and push to master
on:
  pull_request:
    branches:
      - master

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup
        run: |
          mkdir tmp
          git fetch origin master:master
          git diff --name-only master $HEAD > tmp/modified
          npm install -g markdownlint-cli cspell markdown-link-check
          echo "these files have changed"
          cat tmp/modified
  Lint:
    runs-on: ubuntu-latest
    needs: Setup      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Lint
        run: | 
          for file_name in $(cat tmp/modified); do markdownlint $file_name; done                 
  Spelling:
    runs-on: ubuntu-latest
    needs: Setup      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Spelling
        run: | 
          for file_name in $(cat tmp/modified); do cspell $file_name; done   
  Links:
    runs-on: ubuntu-latest
    needs: Setup      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Links
        run: | 
          git diff --name-only $HEAD master > tmp/modified | find . -type f -name '*.md' | xargs -L1 npx markdown-link-check --quiet             